<?php
/**
 * * Klaviyo Feed: 
 * * Usage: Application will query SO for finalized and open orders. For each order sciript will generate a customer profile 
 * * array that will hold customer information such as contacts information, what customer purchased. It will also generate a generate  
 * * an array that will hold detail information about what the customer bought. Script will also track and post customer prospects 
 * * information to klaviyo There will be two CSVs generated by this script one for customers, and the other to track orders, and placed
 * * in the out folder. 
 * * Arguments: 
 * *        - Empty will use yesterday date  
 * *        - 2 Dates: 12-May-21, 13-May-21
 * *
 * * Out: CSVs generated files
 * *---------------------------------------------------------------------------------------------------------------------
 * * 01/11/21   JL  Created Script
 * * 01/13/21   JL  Added comments, and changed structure for customer prospects
 * *
 * *
***/

    date_default_timezone_set('America/Los_Angeles');

    set_include_path('./libs/phpseclib');

    include_once('../config.php');
    include_once('autoload.php');
    include_once('Net/SFTP.php');

    define('NET_SFTP_LOGGING', NET_SFTP_LOG_COMPLEX);

    global $appconfig, $logger;

    $logger = new ILog($appconfig['klaviyo']['logger']['username'], date('ymdhms') . ".log", $appconfig['klaviyo']['logger']['log_folder'], $appconfig['klaviyo']['logger']['priority']);
    $mor = new Morcommon();
    $db = $mor->standAloneAppConnect();
    
    if ( !$db ){
        $logger->error( "Could not connect to database" );
        exit(1);
    }
    $logger->debug( "Starting process: klaviyo feed" );

    //Set default date variables
    $fromDate = new IDate();
    $fromDate = $fromDate->setDate( date('m/d/Y',strtotime("-1 days")), IDate::ORACLE_FORMAT );
    $toDate = new IDate();
    $toDate = $toDate->toStringOracle();

    if( $argc > 1 ){
        $fromDate = $from->setDate( $argv[1] );
        $fromDate = $fromDate->toStringOracle();
        $toDate = $toDate->setDate( $argv[2] );
        $toDate = $toDate->toStringOracle();
    }

    $customerFilename = sprintf( $appconfig['klaviyo']['filename'], 'customers', date("YmdHis") ); 
    $ordersFilename = sprintf( $appconfig['klaviyo']['filename'], 'order_items', date("YmdHis") ); 


    // Processing Finalized Orders
    $logger->debug( "Processing finalized orders" );
    $finalizedSales = processFinalizedOrders( $db, $fromDate, $toDate );
    var_dump($finalizedSales);
    $profile_chunks = array_chunk( $finalizedSales['profiles'], 100 );
    $logger->debug( "Posting to klaviyo finalized orders" );
    $klaviyoPost = postToKlaviyo( $appconfig['klaviyo']['master_list_endpoint'], $profile_chunks, array('Content-Type:application/json'));
    $error = generateCSV( $finalizedSales['profiles'], $customerFilename, $appconfig['klaviyo']['order_profile_header'] );
    if ( $error ) $logger->error( "Error generating csv for finalized orders" );
    $logger->debug( "Finished processing finalized orders" );
    
    //Processing finalized orders lines
    $logger->debug( "Processing finalized orders lines" );
    $finalizedOrders = processInvoices( $db, $finalizedSales['invoices'] );
    $profile_chunks = array_chunk( $finalizedOrders['events'], 100 );
    $logger->debug( "Posting to klaviyo finalized orders lines" );
    $klaviyoPost = postKlaviyoTrackEvents( $appconfig['klaviyo']['track_endpoint'], $finalizedOrders['events'], array('Accept' => 'text/html', 'Content-Type' => 'application/x-www-form-urlencoded') );
    //Generate CSV and upload to SFTP
    $error = generateCSV($finalizedOrders['orders'], $ordersFilename, $appconfig['klaviyo']['order_invoice_header'] );
    if ( $error ) $logger->error( "Error generating csv for finalized orders lines" );
    $logger->debug( "Finished finalized orders lines" );


    //Processing Open Orders
    $logger->debug( "Processing open orders" );
    $openOrders = processOpenOrders( $db, $fromDate, $toDate );
    $profile_chunks = array_chunk( $openOrders['profiles'], 100 );
    $logger->debug( "Posting to klaviyo open orders" );
    $klaviyoPost = postToKlaviyo( $appconfig['klaviyo']['master_list_endpoint'], $profile_chunks, array('Content-Type:application/json') );
    $error = generateCSV( $openOrders['profiles'], $customerFilename, '' );
    if ( $error ) $logger->error( "Could not generate CSV file for open orders" );
    $logger->debug( "Finished processing open orders" );
    
    //Processing open orders lines
    $logger->debug( "Processing open orders lines" );
    $openOrdersEvents = processInvoices( $db, $openOrders['invoices'] );
    $openOrdersEventsChunks = array_chunk( $openOrdersEvents['events'], 100 );
    $logger->debug( "Posting to klaviyo open orders lines" );
    $klaviyoPost = postKlaviyoTrackEvents( $appconfig['klaviyo']['track_endpoint'], $openOrdersEventsChunks, array('Accept: text/html', 'Content-Type: application/x-www-form-urlencoded') );
    $logger->debug( "Generating CSV for open orders" );
    $error = generateCSV($openOrdersEvents['orders'], $ordersFilename, '' );
    if ( $error ) $logger->error( "Could not generate CSV file for open orders lines" );
    $logger->debug( "Finished processing open orders lines" );


    //Processing Customer Prospects 
    $logger->debug( "Querying customer prospects" );
    $prospects = processCustomerProspects( $db, $fromDate, $toDate );
    $prospectsChunks = array_chunk($prospects, 100 );
    $logger->debug( "Posting customer prospects to  klaviyo" );
    $klaviyoPost = postToKlaviyo( $appconfig['klaviyo']['track_prospects'], $prospectsChunks, array('Content-Type:application/json') );
    $error = generateCSV( $prospects, $customerFilename, ''  );
    if( $error ) $logger->error("Could not Create CSV file for customer prospects" );

    $logger->debug( "Finishing process: klaviyo feed" );
    //END EXECUTION

    function upload($filename ){
        global $appconfig, $logger;

        $sftp = new Net_SFTP($appconfig['sftp']['host']);
        if (!$sftp->login($appconfig['sftp']['username'], $appconfig['sftp']['pw'])) {
            //Log error statement
            $logger->error("SFTP connection failed could not upload filename: " . $filename);
            //exit(1);
        }
        else{
            $upload = $sftp->put( $appconfig['klaviyo']['remote_sftp_path'] . $filename, $appconfig['klaviyo']['out'] . $filename, NET_SFTP_LOCAL_FILE );
        }
    }

    function getFinanceCustomerInfo ( $db, $customerCode ){
        $custAsp = new CustAsp($db);
        $where = "WHERE CUST_CD = '" . $customerCode . "'";
        $result = $custAsp->query($where);

        //Initializing data and condition variables for financing data
        $financeCustomerInfo = [ 
            'SYF' => [ 'OPEN_TO_BUY' => 0, 'HAS_ACCT' => 'N' ],
            'AFF' => [ 'OPEN_TO_BUY' => 0, 'HAS_ACCT' => 'N' ],
            'GENE' => [ 'OPEN_TO_BUY' => 0, 'HAS_ACCT' => 'N' ]
        ];

        //Iterating through result set of SQL query on CUST_ASP for customer finance information
        while ($custAsp->next()) {
            $finance[$custAsp->get_AS_CD()]['OPEN_TO_BUY'] = $custAsp->get_APP_CREDIT_AVAIL();
            $finance[$custAsp->get_AS_CD()]['HAS_ACCT'] = 'Y';
        }
        return $financeCustomerInfo;
    }

    function postKlaviyoTrackEvents( $url, $data, $headers ){
        global $appconfig, $logger; 

        $result = '';
        foreach( $data as $d ){
            $ch = curl_init($url);
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_POST, true);

            $body = json_encode($d);
            $body = ltrim($body, '[' );
            $body = rtrim($body, ']' );
            curl_setopt($ch, CURLOPT_POSTFIELDS, "data=".$body);

            $output = curl_exec($ch);
            $info = curl_getinfo($ch);
            curl_close($ch);

            $logger->debug("POST klaviyo track events " . print_r($output, 1) );
        }
        return $data;

    }

    function postToKlaviyo( $url, $data, $headers ){
        global $appconfig, $logger; 

        $result = '';
        //Performing cURL HTTP POST on profiles and orders JSON objects and echoing return JSON objects
        foreach ($data as $d) {
            $ch = curl_init($url);
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

            $body = array();
            $body['api_key'] = $appconfig['klaviyo']['api_key'];
            $body['profiles'] = $d;
            $body = json_encode($body);

            curl_setopt($ch, CURLOPT_POSTFIELDS, $body);

            $result = curl_exec($ch);
            $data = json_decode($result);
            $logger->debug("POST klaviyo " . print_r($result, 3) );
        }
        return $data;

    }

    function getSalesOrderLines( $db, $delDocNum ){
        //Querying for individual SKUs on single invoice
        $tabSOLn = new SOLine($db);
        $where = "WHERE DEL_DOC_NUM = '$delDocNum'";
        $resultSOLn = $tabSOLn->query($where);

        $subtotal = 0;

        //Iterating through result set of SQL query on SO_LN for individual SKUs for single invoice
        while ($tabSOLn->next()) {
            //Adding item's unit price to subtotal
            $subtotal += $tabSOLn->get_UNIT_PRC() * $tabSOLn->get_QTY();
        }

        return $subtotal;
    }


    //Function to generate CSV for uploaded data
    function generateCSV( $data, $filename, $header='' ) {
        global $appconfig, $logger;
        //Generating timestamp CSV file name
        try {
            $file = fopen( $appconfig['klaviyo']['out'] . $filename, "a+" );
            if ( $header !== '' ){
                fputcsv( $file, $header );
            }
            foreach( $data as $line ) {
                fputcsv( $file, array_values($line) );
            }
            fclose($file);

            return false;
        }
        catch( Exception $e ){
            $logger->debug( "Generating CSV Exception caused: " . $e->getMessage() );
            return true;
        }
    }

    function getCustOrders($db,$custCd) {
        $tabSO = new SalesOrder($db);
        $where = "WHERE SO.CUST_CD = '$custCd' AND STAT_CD = 'F'";
        $result = $tabSO->query($where);
        $count = 0;
        $grandTotal = 0;
        while ($tabSO->next()) {
            $count++;
            $subtotal = 0;
            $delDocNum = $tabSO->get_DEL_DOC_NUM();
            $taxChg = $tabSO->get_TAX_CHG();
            $setupChg = $tabSO->get_SETUP_CHG();
            $tabSOLn = new SOLine($db);
            $where = "WHERE DEL_DOC_NUM = '$delDocNum'";
            $result = $tabSOLn->query($where);
            while ($tabSOLn->next()) {
                $subtotal += $tabSOLn->get_UNIT_PRC() * $tabSOLn->get_QTY();
            }
            $orderTotal = $subtotal + $taxChg + $setupChg;
            $grandTotal += $orderTotal;
        }
        $return['count'] = $count;
        $return['total'] = $grandTotal;
        return $return;
    }

    function processInvoices( $db, $invoices ){
        global $appconfig;
        $orders = array();
        $events = array();

        //Iterating through invoices from previous query
        foreach ( $invoices as $invoice => $details ) {
            //Initializing instance array for individual SKU
            $order = array();

            //Querying for individual SKUs on single invoice
            $lines = new SOLine($db);
            $where = "WHERE DEL_DOC_NUM = '" . $invoice . "'";
            $result = $lines->query($where);

            if( $result < 0 ){
                $logger->error("Could not query SO_LN" );
                exit(1);
            }

            //Iterating through result set of SQL query on SO_LN for individual SKUs for single invoice
            while ($lines->next()) {
                //Populating instance array with information from SKU's useful data array as well as result set from SO_LN query
                $order['orderNumber'] = $invoice;
                $order['orderDate'] = $details['orderDate'];
                $order['orderStatus'] = $details['orderType'] == 'O' ? 'OPEN' : 'FINALIZED';
                $order['email'] = $details['email'];
                $order['orderTotal'] = number_format( floatval(preg_replace('/[^\d\.]/', '', $details['subtotal'])) + $details['taxChg'] + $details['setupChg'], 2 );
                $order['orderSubtotal'] = $details['subtotal'];
                $order['taxAmt'] = $details['taxChg'];
                $order['shipAmt'] = '0';
                $order['SKU'] = $lines->get_ITM_CD();
                $order['qty'] = $lines->get_QTY();
                $order['unitPrice'] = $lines->get_UNIT_PRC();
                $order['totalPrice'] = $lines->get_UNIT_PRC() * $lines->get_QTY();
                $order['deliveryType'] = $lines->get_PU_DEL();
                $order['finalShipDate'] = $details['finalShipDate'];
                $order['safeguard'] = $lines->get_VE_CD() == 'SAFE' ? 'Y' : 'N';

                //Adding single SKU array to orders data array if void flag is not set to 'Y' and quantity is greater than zero
                if ( $lines->get_VOID_FLAG() !== 'Y'  && $lines->get_QTY() !== '0' ){
                    $event = array();
                    $event['token'] = $appconfig['klaviyo']['api_key'];
                    $event['event'] = "Ordered Product";
                    $event['customer_properties'] = array('$email'=>$details['email']);
                    $event['properties'] = $order;

                    array_push( $orders, $order );
                    array_push( $events, $event );
                }
            }
        }
        return array( "orders" => $orders, "events" => $events );
    }

    function processOpenOrders( $db, $fromDate, $toDate ){
        global $appconfig, $logger;

        //Initializing arrays to be populated
        $salesOrders = new SalesOrder($db);

        //SQL WHERE clause is built based on what dates are set; default is to query for yesterday's date, but will query for date range if beginning date is provided
        $where = "WHERE STAT_CD = 'O' AND SO_STORE_CD NOT LIKE 'W%' AND ORD_TP_CD = 'SAL' AND SO_WR_DT BETWEEN '" . $fromDate . "' AND '" . $toDate . "'";
        $result = $salesOrders->query($where);
        if( $result < 0 ){
            $logger->error( "Could not query table Sales Order. Where Clause: " . $where );
            exit(1);
        }

        return processSales( $db, $salesOrders );


    }

    function processFinalizedOrders( $db, $fromDate, $toDate ){
        global $appconfig, $logger;

        //Initializing arrays to be populated
        $profiles = array();
        $invoices = array();
        $salesOrders = new SalesOrder($db);

        //SQL WHERE clause is built based on what dates are set; default is to query for yesterday's date, but will query for date range if beginning date is provided
        $where = "WHERE STAT_CD = 'F' AND SO_STORE_CD NOT LIKE 'W%' AND ORD_TP_CD = 'SAL' AND FINAL_DT BETWEEN '" . $fromDate . "' AND '" . $toDate . "'";
        $result = $salesOrders->query($where);
        if( $result < 0 ){
            $logger->error( "Could not query table Sales Order. Where Clause: " . $where );
            exit(1);
        }

        return processSales( $db, $salesOrders );

    }

    function processSales( $db, $data ){
        global $appconfig; 
        $profiles = array();
        $invoices = array();

        //Iterating through result set of SQL query on SO for finalized orders for date or date range
        while ($data->next()) {
            if ( is_null($data->get_EMAIL_ADDR()) ){
                continue;
            }
            //Creating instance arrays for single customer and invoice
            $profile = array();
            $invoice = array();

            $salesOrderLinesTotal = getSalesOrderLines( $db, $data->get_DEL_DOC_NUM() ); 
            $customerFinanceInfo = getFinanceCustomerInfo( $db, $data->get_CUST_CD() );
            $custTotal = getCustOrders( $db, $data->get_CUST_CD() );

            //Populating instance array for single customer
            $profile['email'] = $data->get_EMAIL_ADDR();
            $profile['firstName'] = $data->get_FNAME();
            $profile['lastName'] = $data->get_LNAME();
            $profile['openToBuyAmount'] = $customerFinanceInfo['SYF']['OPEN_TO_BUY'];
            $profile['emailOptIn'] = "TRUE";
            $profile['SMSOptIn'] = $data->get_USR_FLD_2();
            $profile['address'] = $data->get_SHIP_TO_ADDR1();
            $profile['address2'] = $data->get_SHIP_TO_ADDR2();
            $profile['city'] = $data->get_SHIP_TO_CITY();
            $profile['state'] = $data->get_SHIP_TO_ST_CD();
            $profile['zip'] = $data->get_SHIP_TO_ZIP_CD();
            $profile['phone_number'] = "1".str_replace("-","",$data->get_SHIP_TO_H_PHONE());
            $profile['secondaryPhone'] = "1".str_replace("-","",$data->get_SHIP_TO_B_PHONE());
            $profile['lastStorePurchasedFrom'] = $data->get_SO_STORE_CD();
            $profile['lastLoggedSalespersonId'] = $data->get_SO_EMP_SLSP_CD1();
            $profile['lastLoggedSalespersonDate'] = date_format(new DateTime($data->get_SO_WR_DT()), "n/j/Y");
            $profile['source'] = "buyer";
            $profile['synchronyCreditCard'] = $customerFinanceInfo['SYF']['HAS_ACCT'];
            $profile['PreScreenSynchronyCard'] = $customerFinanceInfo['SYF']['HAS_ACCT'];
            $profile['AFFCard'] = $customerFinanceInfo['AFF']['HAS_ACCT'];
            $profile['genesisCard'] = $customerFinanceInfo['GENE']['HAS_ACCT'];
            $profile['LastOrderDate'] = date_format(new DateTime('yesterday'),'n/j/Y');
            $profile['LastOrderTotal'] = '$' . number_format($salesOrderLinesTotal + $data->get_TAX_CHG() + $data->get_SETUP_CHG(), 2);

            //Getting information on total finalized orders for customer
            $profile['TotalOrders'] = $custTotal['count'];
            $profile['TotalRevenue'] = $custTotal['total'];
            $profile['AverageOrderValue'] = $custTotal['total'] != 0 ? number_format($custTotal['total'] / $custTotal['count'], 2) : $custTotal['total'];

            //Checking condition variables; omitting profile if no email is set, email address is set to unsubscribe, or salesperson has been terminated
            if ( !is_null($profile['email']) ){
                if ( $profile['email'] !== 'NSUBSCRIB' && is_null($data->get_TERMDATE()) ) {
                    //Adding single customer array to profiles data array
                    array_push($profiles, $profile);

                    //Creating instance array for invoice to query for SKU data for orders data array; del doc num will be key and array of useful data will be value
                    $invoice['orderDate'] = date_format(new DateTime($data->get_SO_WR_DT()), "n/j/Y g:i");
                    $invoice['orderType'] = $data->get_STAT_CD() == 'O' ? 'OPEN' : 'FINALIZED';
                    $invoice['email'] = $data->get_EMAIL_ADDR();
                    $invoice['subtotal'] = '$' . number_format($salesOrderLinesTotal, 2);
                    $invoice['taxChg'] = $data->get_TAX_CHG();
                    $invoice['setupChg'] = $data->get_SETUP_CHG();

                    $puDelDt = date_create( $data->get_PU_DEL_DT() );
                    $invoice['finalShipDate'] = date_format($puDelDt,"n/j/Y g:i");
                    $invoices[$data->get_DEL_DOC_NUM()] = $invoice;
                }
            }
        }

        return array( 'profiles' => $profiles, 'invoices' => $invoices );

    }

    function processCustomerProspects( $db, $fromDate, $toDate ){
        global $appconfig, $logger;
        $prospects = new CustomerProspects($db);
        $where = "WHERE CREATED_AT > '" . $fromDate . "' AND CREATED_AT <= '" . $toDate . "' ";

        $result = $prospects->query($where);
        if ( $result < 0 ){
           $logger->debug( "ERROR querying table cust_prospect" ); 
           exit(1);
        }
        $customers = array();
        while( $prospects->next() ){
            $tmp = [
                'email' => $prospects->get_EMAIL(),
                'firstName' => $prospects->get_FNAME(),
                'lastName' => $prospects->get_LNAME(),
                'openToBuyAmount' => '',
                'emailOptIn' => '', 
                'SMSOptIn' => '',
                'address' => '',
                'address2' => '',
                'city' => '',
                'state' => '',
                'phone_number' => "1" . str_replace("-", "", $prospects->get_PHONE()),
                'secondaryPhone' => '',
                'lastStorePurchasedFrom' => '',
                'lastLoggedSalesPersonId' => $prospects->get_EMP_CD(),
                'lastLoggedSalespersonDate' => '',
                'source' => 'prospect',
                'synchronyCreditCard' => '',
                'PreScreenSynchronyCard' => '',
                'AFFCard' => '',
                'genesisCard' => '',
                'LastOrderDate' => '',
                'LastOrderTotal' => '',
                'TotalOrders' => '',
                'TotalRevenue' => '',
                'AverageOrderValue' => '',
            ];
            
            array_push( $customers, $tmp );
        }

            var_dump($customers);
        return $customers;


    }
    


?>
